### ISSUE TITLE
Support loading gem on all (recent) versions of JRuby

### ISSUE THREAD

**Issue by rtyler** [lookout/fast-rsa-engine#6] opened 2015-07-26 15:21 UTC
I think being able to safely require, regardless of whether we can implement the faster engine, on any version of JRuby is important.

That way we can safely add it as a transitive dependency for internal gems, regardless of what version of JRuby is being executed

**Comment by rtyler** [comment] 2015-08-10 21:10
@mkristian you had a chance to tackle this yet?

**Comment by mkristian** [comment] 2015-08-11 07:14
the problem is the jruby-openssl version used. 0.9.6 is too old, i.e. then the gem will has no effect as in the MRI case.

this got fixed with https://github.com/lookout/fast-rsa-engine/commit/64a5aa4c7db82175741c0e6cb3c77a736dbe6c77

**Closed by mkristian** 2015-08-11 07:14 UTC
Labels: enhancement
